import type { Metadata } from "next";
import iransansFont from "next/font/local";
import "./styles/globals.scss";
import TanstackProvider from "./providers/TanstackProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import StoreProvider from "./providers/StoreProvider";

const iransans = iransansFont({
  src: "../public/assets/fonts/IRANSans-Regular.ttf",
});

export const metadata: Metadata = {
  title: "Snapp Food",
  description: "Generated by Mehrshad Karimi",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={iransans.className}>
        <TanstackProvider>
          <StoreProvider>{children}</StoreProvider>
        </TanstackProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
